### ISSUE TITLE
OS X 10.9 - Compilation error

### ISSUE THREAD

**Issue by andreadelprete** [robotology-playground/WBI-Toolbox#2]
I'm experiencing a problem when trying to run any simulink controller using the WBI-Toolbox. I installed CoDyCo-superbuild on Mac OS X 10.9 and I'm using Matlab 2013a. When I try to run (e.g.) ```controllerWithHandControl.slx``` (located in the folder ```torqueBalancing```) I get the following error:
```
Making simulation target "WBCLibrary_sfun", ... 

/Applications/MATLAB_R2013a.app/bin/mex -c -O  -DMATLAB_MEX_FILE    -I/Applications/MATLAB_R2013a.app/stateflow/c/mex/include -I/Applications/MATLAB_R2013a.app/stateflow/c/debugger/include   WBCLibrary_sfun.c
In file included from WBCLibrary_sfun.c:3:
In file included from ./WBCLibrary_sfun.h:6:
In file included from /Applications/MATLAB_R2013a.app/stateflow/c/mex/include/sfc_sf.h:33:
In file included from /Applications/MATLAB_R2013a.app/simulink/include/mwmathutil.h:23:
/Applications/MATLAB_R2013a.app/extern/include/tmwtypes.h:819:9: error: unknown type
      name 'char16_t'
typedef char16_t CHAR16_T;
        ^
1 error generated.
    mex: compile of ' "WBCLibrary_sfun.c"' failed.
gmake: *** [WBCLibrary_sfun.o] Error 1
```
With the help of @francesco-romano I tried to solve it by modifying the Matlab's configuration file ```mexopts.sh``` so as to force the use of the c++11 standard library (because char16t has been introduced in c++11):
```
maci64)
#----------------------------------------------------------------------------
            # StorageVersion: 1.0
            # CkeyName: Clang
            # CkeyManufacturer: Apple
            # CkeyLanguage: C
            # CkeyVersion:
            # CkeyLinkerName:
            # CkeyLinkerVersion:
#CC='xcrun  -sdk macosx10.9  clang'
CC='clang'
## workaround clang defect temporarily use line below           SDKROOT='/Developer/SDKs/MacOSX10.6.sdk'
# compute SDK root on the fly
# target 10.7 
            MW_SDK_TEMP="find `xcode-select -print-path` -name MacOSX10.9.sdk"
            MW_SDKROOT=`$MW_SDK_TEMP`
            MACOSX_DEPLOYMENT_TARGET='10.9'
            ARCHS='x86_64'
            CFLAGS="-fno-common -arch $ARCHS -isysroot $MW_SDKROOT -mmacosx-version-min=$MACOSX_DEPLOYMENT_TARGET"
            CFLAGS="$CFLAGS  -fexceptions"
            CLIBS="$MLIBS"
            COPTIMFLAGS='-O2 -DNDEBUG'
            CDEBUGFLAGS='-g'
#
#CLIBS="$CLIBS -lstdc++"
            CLIBS="$CLIBS"
            # C++keyName: Clang++
            # C++keyManufacturer: Apple
            # C++keyLanguage: C++
            # C++keyVersion:
            # C++keyLinkerName:
            # C++keyLinkerVersion:
            CXX='clang++'
            CXXFLAGS="-fno-common -fexceptions -arch $ARCHS -isysroot $MW_SDKROOT -mmacosx-version-min=$MACOSX_DEPLOYMENT_TARGET -std=c++11"
#            CXXLIBS="$MLIBS -lstdc++"
            CXXLIBS="$MLIBS"
            CXXOPTIMFLAGS='-O2 -DNDEBUG'
            CXXDEBUGFLAGS='-g'
```
Unfortunately, this had no effect on the error. To try and solve this problem @francesco-romano and I would like to gain an insight into the steps taken by simulink when one runs the model. In particular, why is simulink trying to compile ```WBCLibrary_sfun.c``` to generate a mex file? I thought all mex files were generated when compiling the WBI toolbox. Maybe @jeljaik can help us on this?

**Comment by jeljaik** [comment]
Closing as solution has been  described above and no feedback was ever given.
